[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"



[project]
name = "invoice-pipeline"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "magika",
    "pypdf",
    "resvg_py",
]


[dependency-groups]
dev = [
    "pytest",
    "databricks-sdk>=0.73.0",
    "databricks-connect>=17.0,<17.3",
    "pyspark>=3.5.0",
    "pandas-stubs",
    "wrapt>=2.0.0",
]


[tool.uv_build]
package-dir = { "" = "src" }



